FROM golang:1.21-alpine AS builder

WORKDIR /build
COPY server/ .
RUN go mod tidy
RUN go mod download
RUN go build -o sss-storage-server main.go

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /build/sss-storage-server /usr/local/bin/sss-storage-server
EXPOSE 8080
CMD ["sss-storage-server"]
